import "unknwn.idl" ;
/* IMyMath Interface */
[
    object,
    uuid(349BB164-9B46-4F39-A0DB-CD5670553AE1), /* IID of MyMath */
    helpstring("IMyMath Interface"),
    pointer_default(unique),
    dual,
    oleautomation
]
interface IMyMath : IDispatch
{
    import "oaidl.idl";
    HRESULT SumOfTwoIntegers([in]int, [in]int, [out, retval]int*);
    HRESULT SubtractionOfTwoIntegers([in]int, [in]int, [out, retval]int*);
};
/* Actual TypeLib related code */
[
    uuid(A62EFEB5-DAD8-4481-ACC0-3ADE520E94A7), /* LIBID of Type Library */
    version(1.0),
    helpstring("MyMathAutomation component's type library")
]
library AutomationDllServerWithRegFileTypeLib
{
    importlib("stdole32.tlb");
    /* component code */
    [
        uuid(28DD1A38-635C-41F6-843F-59B951417791),     /* CLSID of MyMath component */
        helpstring("MyMathAutomation component class")
    ]
    coclass CMyMath
    {
        [default]interface IMyMath;
    };
};
