; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

	TITLE	c:\Win32Projects(VS2019)\CMD\32Bit\MyFirstWindow\MyFirstWindow.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG89569 DB	'My Application', 00H
	ORG $+1
$SG89570 DB	'My Window', 00H
CONST	ENDS
PUBLIC	_WinMain@16
PUBLIC	?WndProc@@YGJPAUHWND__@@IIJ@Z			; WndProc
EXTRN	_memset:PROC
EXTRN	__imp__GetStockObject@4:PROC
EXTRN	__imp__GetMessageA@16:PROC
EXTRN	__imp__TranslateMessage@4:PROC
EXTRN	__imp__DispatchMessageA@4:PROC
EXTRN	__imp__DefWindowProcA@16:PROC
EXTRN	__imp__PostQuitMessage@4:PROC
EXTRN	__imp__RegisterClassExA@4:PROC
EXTRN	__imp__CreateWindowExA@48:PROC
EXTRN	__imp__ShowWindow@8:PROC
EXTRN	__imp__UpdateWindow@4:PROC
EXTRN	__imp__LoadCursorA@8:PROC
EXTRN	__imp__LoadIconA@8:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___security_cookie:DWORD
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv64 = -4						; size = 4
_hwnd$ = 8						; size = 4
_iMsg$ = 12						; size = 4
_wParam$ = 16						; size = 4
_lParam$ = 20						; size = 4
?WndProc@@YGJPAUHWND__@@IIJ@Z PROC			; WndProc
; File c:\Win32Projects(VS2019)\CMD\32Bit\MyFirstWindow\MyFirstWindow.cpp
; Line 72
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 73
	mov	eax, DWORD PTR _iMsg$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 2
	je	SHORT $LN4@WndProc
	jmp	SHORT $LN2@WndProc
$LN4@WndProc:
; Line 76
	push	0
	call	DWORD PTR __imp__PostQuitMessage@4
$LN2@WndProc:
; Line 80
	mov	ecx, DWORD PTR _lParam$[ebp]
	push	ecx
	mov	edx, DWORD PTR _wParam$[ebp]
	push	edx
	mov	eax, DWORD PTR _iMsg$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hwnd$[ebp]
	push	ecx
	call	DWORD PTR __imp__DefWindowProcA@16
; Line 81
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
?WndProc@@YGJPAUHWND__@@IIJ@Z ENDP			; WndProc
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_msg$ = -100						; size = 28
_wndclass$ = -72					; size = 48
_hwnd$ = -24						; size = 4
_szAppName$ = -20					; size = 15
__$ArrayPad$ = -4					; size = 4
_hInstance$ = 8						; size = 4
_hPrevInstance$ = 12					; size = 4
_lpszCmdLine$ = 16					; size = 4
_iCmdShow$ = 20						; size = 4
_WinMain@16 PROC
; File c:\Win32Projects(VS2019)\CMD\32Bit\MyFirstWindow\MyFirstWindow.cpp
; Line 12
	push	ebp
	mov	ebp, esp
	sub	esp, 100				; 00000064H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 17
	mov	eax, DWORD PTR $SG89569
	mov	DWORD PTR _szAppName$[ebp], eax
	mov	ecx, DWORD PTR $SG89569+4
	mov	DWORD PTR _szAppName$[ebp+4], ecx
	mov	edx, DWORD PTR $SG89569+8
	mov	DWORD PTR _szAppName$[ebp+8], edx
	mov	ax, WORD PTR $SG89569+12
	mov	WORD PTR _szAppName$[ebp+12], ax
	mov	cl, BYTE PTR $SG89569+14
	mov	BYTE PTR _szAppName$[ebp+14], cl
; Line 22
	push	48					; 00000030H
	push	0
	lea	edx, DWORD PTR _wndclass$[ebp]
	push	edx
	call	_memset
	add	esp, 12					; 0000000cH
; Line 25
	mov	DWORD PTR _wndclass$[ebp], 48		; 00000030H
; Line 26
	mov	DWORD PTR _wndclass$[ebp+4], 3
; Line 27
	mov	DWORD PTR _wndclass$[ebp+12], 0
; Line 28
	mov	DWORD PTR _wndclass$[ebp+16], 0
; Line 29
	mov	DWORD PTR _wndclass$[ebp+8], OFFSET ?WndProc@@YGJPAUHWND__@@IIJ@Z ; WndProc
; Line 30
	mov	eax, DWORD PTR _hInstance$[ebp]
	mov	DWORD PTR _wndclass$[ebp+20], eax
; Line 31
	push	32512					; 00007f00H
	push	0
	call	DWORD PTR __imp__LoadIconA@8
	mov	DWORD PTR _wndclass$[ebp+24], eax
; Line 32
	push	32512					; 00007f00H
	push	0
	call	DWORD PTR __imp__LoadCursorA@8
	mov	DWORD PTR _wndclass$[ebp+28], eax
; Line 33
	push	32512					; 00007f00H
	push	0
	call	DWORD PTR __imp__LoadIconA@8
	mov	DWORD PTR _wndclass$[ebp+44], eax
; Line 34
	push	2
	call	DWORD PTR __imp__GetStockObject@4
	mov	DWORD PTR _wndclass$[ebp+32], eax
; Line 35
	lea	ecx, DWORD PTR _szAppName$[ebp]
	mov	DWORD PTR _wndclass$[ebp+40], ecx
; Line 36
	mov	DWORD PTR _wndclass$[ebp+36], 0
; Line 39
	lea	edx, DWORD PTR _wndclass$[ebp]
	push	edx
	call	DWORD PTR __imp__RegisterClassExA@4
; Line 43
	push	0
	mov	eax, DWORD PTR _hInstance$[ebp]
	push	eax
	push	0
	push	0
	push	-2147483648				; 80000000H
	push	-2147483648				; 80000000H
	push	-2147483648				; 80000000H
	push	-2147483648				; 80000000H
	push	13565952				; 00cf0000H
	push	OFFSET $SG89570
	lea	ecx, DWORD PTR _szAppName$[ebp]
	push	ecx
	push	0
	call	DWORD PTR __imp__CreateWindowExA@48
	mov	DWORD PTR _hwnd$[ebp], eax
; Line 58
	mov	edx, DWORD PTR _iCmdShow$[ebp]
	push	edx
	mov	eax, DWORD PTR _hwnd$[ebp]
	push	eax
	call	DWORD PTR __imp__ShowWindow@8
; Line 59
	mov	ecx, DWORD PTR _hwnd$[ebp]
	push	ecx
	call	DWORD PTR __imp__UpdateWindow@4
$LN2@WinMain:
; Line 62
	push	0
	push	0
	push	0
	lea	edx, DWORD PTR _msg$[ebp]
	push	edx
	call	DWORD PTR __imp__GetMessageA@16
	test	eax, eax
	je	SHORT $LN3@WinMain
; Line 64
	lea	eax, DWORD PTR _msg$[ebp]
	push	eax
	call	DWORD PTR __imp__TranslateMessage@4
; Line 65
	lea	ecx, DWORD PTR _msg$[ebp]
	push	ecx
	call	DWORD PTR __imp__DispatchMessageA@4
; Line 66
	jmp	SHORT $LN2@WinMain
$LN3@WinMain:
; Line 68
	mov	eax, DWORD PTR _msg$[ebp+8]
; Line 69
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
_WinMain@16 ENDP
_TEXT	ENDS
END
