import "unknwn.idl" ;
/* IMyMath Interface */
[
    object,
    uuid(D3172311-1903-46C8-948B-A03EE8DC58C7), /* IID of MyMath */
    helpstring("IMyMath Interface"),
    pointer_default(unique),
    dual,
    oleautomation
]
interface IMyMath : IDispatch
{
    import "oaidl.idl";
    HRESULT SumOfTwoIntegers([in]int, [in]int, [out, retval]int*);
    HRESULT SubtractionOfTwoIntegers([in]int, [in]int, [out, retval]int*);
};
/* Actual TypeLib related code */
[
    uuid(6520512F-BC21-470F-A1A0-1338094D4AE6), /* LIBID of Type Library */
    version(1.0),
    helpstring("MyMathAutomation component's type library")
]
library AutomationDllServerWithRegFileTypeLib
{
    importlib("stdole32.tlb");
    /* component code */
    [
        uuid(6D5FD802-4FC6-4B51-ABBC-1BC52707B8E1),     /* CLSID of MyMath component */
        helpstring("MyMathAutomation component class")
    ]
    coclass CMyMath
    {
        [default]interface IMyMath;
    };
};
